name: care-core

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: cms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [care-net]

  auth-service:
    build: ./auth-service
    environment:
      SERVER_PORT: "8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cms_db
      DB_USERNAME: postgres
      DB_PASSWORD: P@ssw0rd
      # JWT_SECRET: <set if needed>
    depends_on: [postgres]
    ports:
      - "6061:8080"
    networks: [care-net]

  access-management-service:
    build: ./access-management-system
    environment:
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cms_db
      DB_USERNAME: postgres
      DB_PASSWORD: P@ssw0rd
    depends_on: [postgres]
    ports:
      - "6062:8080"
    networks: [care-net]

  gateway-service:
    build: ./gateway-service
    environment:
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: SuperSecureKeyThatIsAtLeast64CharactersLongToAvoidWeakKeyException1234567890
    depends_on: [auth-service, access-management-service]
    ports:
      - "6060:8080"
    networks: [care-net]

volumes:
  pgdata:

networks:
  care-net:
