# Configuration specific to data-analysis-service
# Port: 6072, Database: das_db

server:
  port: 6072

spring:
  application:
    name: data-analysis-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:das_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:P@ssw0rd}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  cloud:
    discovery:
      enabled: false

jwt:
  secret: ${JWT_SECRET:SuperSecureKeyThatIsAtLeast64CharactersLongToAvoidWeakKeyException1234567890}

storage:
  root: storage/

care:
  security:
    internal-key: ${INTERNAL_KEY:dev-internal-key}

